###SHOW FOLDER
GET /api/folders HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgyMTU0NzA2LCJleHAiOjE2ODIxNzI3MDZ9.v4Pi1PaIPPSSbaCjeIgikOtdGIh1ZSAHo4JSheUuJ80

###ADD FOLDER
POST /api/folders HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgyMTczNTIxLCJleHAiOjE2ODIxOTE1MjF9.PGZPqmR2_UDqa8UcXh7QM8-FvBH13YQt9VR5s57diUc
Content-Type: application/json

{"folder1": [],"folder2": []}

###REMOVE FOLDER
DELETE /api/folders/folder1&folder2 HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgyMTczNTIxLCJleHAiOjE2ODIxOTE1MjF9.PGZPqmR2_UDqa8UcXh7QM8-FvBH13YQt9VR5s57diUc

