###SHOW FOLDER
GET /api/folders HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgzMTA4MzE1LCJleHAiOjE2ODMxMjYzMTV9.LdVhEE7AVNP5tlmCnCQZQAbKR1dKsiGctLXOpPXuQNQ

###ADD FOLDER
POST /api/folders HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgyMzM3ODczLCJleHAiOjE2ODIzNTU4NzN9.fct299WEUpl2BhK2_auu0bV6qCOb8iTAapNXcHKr5LI
Content-Type: application/json

{"newfolder": "newf233k=--0;"}

###REMOVE FOLDER
DELETE /api/folders/folder1&folder2 HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgyMTczNTIxLCJleHAiOjE2ODIxOTE1MjF9.PGZPqmR2_UDqa8UcXh7QM8-FvBH13YQt9VR5s57diUc


###CHANGE FOLDER NAME
POST /api/folders/change HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgyMzMwMTE3LCJleHAiOjE2ODIzNDgxMTd9.WAsnCFhlJ64YJRCWRrSnpn52BPER7a9UCT1GOjnwumg
Content-Type: application/json

{"oldName": "folder1452", "newName": "folder1"}

###ADD ELEMENT TO FOLDER
POST /api/folders/element HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgyMzQ3NTQxLCJleHAiOjE2ODIzNjU1NDF9.04KxDe89dTR9ume8DNBeJgVkb8aJg9JqJlF2-Ll6zE8
Content-Type: application/json

{"folder": "gg", "element": ["elementID", "elementID2"]}


###REMOVE ELEMENT FROM FOLDER
DELETE /api/folders/element/folder1&elementID2 HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgyMzMwMTE3LCJleHAiOjE2ODIzNDgxMTd9.WAsnCFhlJ64YJRCWRrSnpn52BPER7a9UCT1GOjnwumg

