
###login
POST /api/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"email":"e@email","password":"1234"}


###REGISTRATION
POST /api/register HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"email":"e@piero","password":"1234","name":"name","surname":"surname"}


###SHOW USER VAULT
GET /api/vault HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgxNDYxNjA3LCJleHAiOjE2ODE0Nzk2MDd9.4I_0P0FJI6yfR_J8H2lIkloYZ5BAwDuVNtaKhzL4LP0


###ADD TO VAULT
POST /api/vault HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgxNDYxNjA3LCJleHAiOjE2ODE0Nzk2MDd9.4I_0P0FJI6yfR_J8H2lIkloYZ5BAwDuVNtaKhzL4LP0
Content-Type: application/json

{"name": "nome4","email":"emaildelsito@sito","password":"pass4","link":"sito", "notes":"note sito 4"}


###REMOVE FROM VAULT
DELETE /api/vault HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgxNDg4MDk5LCJleHAiOjE2ODE1MDYwOTl9.Uo3csTKK09Cawd-RYexmPUd9U1dRm4WRdePxohxrydg
Content-Type: application/json

{"elements":["64396b93fb0ccafcb82805e3"]}

###UPDATE ELEMENT
PUT /api/vault HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgxNDg5ODgwLCJleHAiOjE2ODE1MDc4ODB9.mvriDoM2nqJohazFaTRzw-Cm2Oww6ct1WaKPfnK6qbI
Content-Type: application/json


{
  "name": "new",
  "email": "emaildelsito@sito",
  "password": "pass23",
  "site": "sito2s",
}

###REMOVE TAGS
POST /api/vault/643ea24e8c6c851bb27affd9/tags HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgyMDg1ODU1LCJleHAiOjE2ODIxMDM4NTV9.4TgTgoiM90RugOh7tZ8jA7Y2FTw7uoFmPaEcYnCFLgI
Content-Type: application/json

{"list":["folder2"]}

###REMOVE TYPES
POST /api/vault/643ea24e8c6c851bb27affd9/types HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgyMDg1ODU1LCJleHAiOjE2ODIxMDM4NTV9.4TgTgoiM90RugOh7tZ8jA7Y2FTw7uoFmPaEcYnCFLgI
Content-Type: application/json

{"list":["Favorite","Accounts"]}






