
###login
POST /api/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"email":"e@email","password":"1234"}


###REGISTRATION
POST /api/register HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"email":"e@emai1327765ytrfdkksfsy464565rg5gl","password":"1234","name":"name","surname":"surname"}


###SHOW USER VAULT
GET /api/vault HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgwODYwMjExLCJleHAiOjE2ODA4NzgyMTF9.q0ZApnSRWyB9hoz93mf2zMmg3w13VL5updV5JHQsF0M


###ADD TO VAULT
POST /api/vault HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgwNzg2MjQxLCJleHAiOjE2ODA4MDQyNDF9.9iRfHZKQo1HZWJI9fwr12BEiHBTG3yRpH2Me8X-Go8g
Content-Type: application/json

{"name": "nomeacaso","email":"emaildelsito@sito","password":"passsito","link":"sitodelcane", "notes":"note a caso"}


###REMOVE FROM VAULT
DELETE /api/vault/606eba699ef7ddf325fb HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgwNzg2MjQxLCJleHAiOjE2ODA4MDQyNDF9.9iRfHZKQo1HZWJI9fwr12BEiHBTG3yRpH2Me8X-Go8g






