
###login
POST /api/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"email":"e@email","password":"1234"}


###REGISTRATION
POST /api/register HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"email":"e@pippa","password":"1234","name":"name","surname":"surname"}


###CHANGE USER DETAILS
POST /api/user/details HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgzMTM1MDI0LCJleHAiOjE2ODMxNTMwMjR9.BsaJYavKFFG9js_hasYRm0qzVmXMA0FO-ya-MDKgkRU
Content-Type: application/json

{"field":"surname","value":"hocambiastoilcognome"}


###CHANGE USER PASSWORD
POST /api/user/password HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgzMTM1MDI0LCJleHAiOjE2ODMxNTMwMjR9.BsaJYavKFFG9js_hasYRm0qzVmXMA0FO-ya-MDKgkRU
Content-Type: application/json

{"oldpassword":"1234","newpassword":"1234"}


###
GET /testjwt HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoicGlwcG8iLCJzdXJuYW1lIjoiZ3JhbmRlIiwiaWF0IjoxNjgzNjI4MDUxLCJleHAiOjE2ODM2MjgwNjZ9._zr7KZGm8G67p3GovYQ5LMvcIP3dA5J8n5P6QIPQN0Q


###logout
DELETE /api/logout/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoicGlwcG8iLCJzdXJuYW1lIjoiZ3JhbmRlIiwiaWF0IjoxNjgzNjI4NTI5fQ.EXEFOKKFSnJw9aDpf8E1aP4xFxqsHvE7t_5vVcyy9Mo HTTP/1.1
Host: localhost:3000







