
###login
POST /api/user/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"email":"e@piero1234","password":"1234"}


###REGISTRATION
POST /api/user/register HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"email":"e@piero1234","password":"1234","name":"name","surname":"surname"}

###logout
DELETE /api/user/logout?refreshtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoicGlwcG8iLCJzdXJuYW1lIjoiZ3JhbmRlIiwiaWF0IjoxNjg0NDI2ODA3fQ.9xDyyuoMJfGvRG-o81PKH7CViRRVacvqhyeCxeeKltU
Host: localhost:3000

###SHOW USER DETAILS

###CHANGE USER DETAILS
POST /api/user/changedetails HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgzMTM1MDI0LCJleHAiOjE2ODMxNTMwMjR9.BsaJYavKFFG9js_hasYRm0qzVmXMA0FO-ya-MDKgkRU
Content-Type: application/json

{"field":"surname","value":"hocambiastoilcognome"}





###CHANGE USER PASSWORD
POST /api/user/changepassword HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZW1haWwiLCJuYW1lIjoibmFtZSIsInN1cm5hbWUiOiJzdXJuYW1lIiwiaWF0IjoxNjgzMTM1MDI0LCJleHAiOjE2ODMxNTMwMjR9.BsaJYavKFFG9js_hasYRm0qzVmXMA0FO-ya-MDKgkRU
Content-Type: application/json

{"oldpassword":"1234","newpassword":"1234"}







